// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxhkoicpnyjuxynjecaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4aGtvaWNwbnlqdXh5bmplY2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTg4MjgsImV4cCI6MjA2MDk5NDgyOH0.5RzukBiu1cjJEsikUMRHU-R6WslyE7wThvG-y83nuGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);